# Generated by Django 6.0.1 on 2026-01-27 19:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Bootstrap icon class', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sorting order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='gifts.category', verbose_name='Parent category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('tag_type', models.CharField(choices=[('O', 'occasion'), ('R', 'relationship'), ('I', 'interest'), ('A', 'age_group')], max_length=1, verbose_name='Tag type')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['tag_type', 'name'],
                'indexes': [models.Index(fields=['slug'], name='gifts_tag_slug_2cc89f_idx'), models.Index(fields=['tag_type', 'name'], name='gifts_tag_tag_typ_bebfa9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Short description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gifts/')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex')], default='U', max_length=1)),
                ('age_min', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Age min')),
                ('age_max', models.PositiveIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Age max')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Min price')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Max price')),
                ('popularity_score', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gifts.category')),
                ('tags', models.ManyToManyField(blank=True, to='gifts.tag')),
            ],
            options={
                'verbose_name': 'Gift',
                'verbose_name_plural': 'Gifts',
                'ordering': ['-popularity_score', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='gifts_categ_slug_32d691_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'order'], name='gifts_categ_parent__1b52cb_idx'),
        ),
        migrations.AddIndex(
            model_name='gift',
            index=models.Index(fields=['slug'], name='gifts_gift_slug_9c9565_idx'),
        ),
        migrations.AddIndex(
            model_name='gift',
            index=models.Index(fields=['gender', 'age_min', 'age_max'], name='gifts_gift_gender_9ef0da_idx'),
        ),
        migrations.AddIndex(
            model_name='gift',
            index=models.Index(fields=['min_price', 'max_price'], name='gifts_gift_min_pri_5f8b55_idx'),
        ),
        migrations.AddIndex(
            model_name='gift',
            index=models.Index(fields=['-popularity_score', '-created_at'], name='gifts_gift_popular_a557d3_idx'),
        ),
        migrations.AddIndex(
            model_name='gift',
            index=models.Index(fields=['is_active', 'is_featured'], name='gifts_gift_is_acti_c7a538_idx'),
        ),
        migrations.AddConstraint(
            model_name='gift',
            constraint=models.CheckConstraint(condition=models.Q(('age_min__lte', models.F('age_max'))), name='age_min_lte_age_max'),
        ),
    ]
