# Generated by Django 6.0.1 on 2026-01-27 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gifts/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gifts.gift')),
            ],
            options={
                'verbose_name': 'Gift Image',
                'verbose_name_plural': 'Gift Images',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['gift', 'order'], name='gifts_gifti_gift_id_994085_idx')],
            },
        ),
    ]
