# Generated by Django 6.0.1 on 2026-05-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gifts", "0003_gift_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="gift",
            name="catalog_source",
            field=models.CharField(
                blank=True,
                choices=[("hotline", "Hotline")],
                db_index=True,
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="gift",
            name="source_product_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="gift",
            name="source_product_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddIndex(
            model_name="gift",
            index=models.Index(
                fields=["catalog_source", "source_product_id"],
                name="gifts_gift_catalog_83bc5e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="gift",
            constraint=models.UniqueConstraint(
                condition=~models.Q(catalog_source="") & ~models.Q(source_product_id=""),
                fields=("catalog_source", "source_product_id"),
                name="unique_catalog_source_product_id",
            ),
        ),
    ]
