from __future__ import annotations
from dataclasses import dataclass

@dataclass(frozen=True)
class HotlineSeedTemplate:
    key: str
    query: str
    category_slug: str
    category_name: str
    source_url: str = ""
    parent_slug: str = ""
    parent_name: str = ""
    priority: int = 100

OBSOLETE_HOTLINE_SEED_KEYS: tuple[str, ...] = (
    "gaming-consoles",
    "gaming-handheld-consoles",
    "gaming-gamepads",
    "gaming-headsets",
    "gaming-mice",
    "gaming-keyboards",
    "electronics-smartphones",
    "electronics-smartwatches",
    "electronics-tablets",
    "electronics-headphones",
    "electronics-powerbanks",
    "home-coffee-machines",
    "home-robot-vacuums",
    "home-air-fryers",
    "beauty-hair-dryers",
    "beauty-shavers",
    "fashion-backpacks",
    "sports-dumbbells",
    "auto-dash-cams",
    "toys-lego",
    "office-chairs",
    "travel-suitcases",
)

HOTLINE_SEED_TEMPLATES: tuple[HotlineSeedTemplate, ...] = (
    HotlineSeedTemplate('power-energy', 'Енергозабезпечення', 'power-energy', 'Енергозабезпечення', 'https://hotline.ua/ua/power/energy/', 'power', 'Енергозабезпечення', 1010),
    HotlineSeedTemplate('power-internet-bez-svitla', 'Інтернет без світла', 'power-internet-bez-svitla', 'Інтернет без світла', 'https://hotline.ua/ua/power/internet-bez-svitla/', 'power', 'Енергозабезпечення', 1020),
    HotlineSeedTemplate('power-energosberezhennya', 'Енергозбереження', 'power-energosberezhennya', 'Енергозбереження', 'https://hotline.ua/ua/power/energosberezhennya/', 'power', 'Енергозабезпечення', 1030),
    HotlineSeedTemplate('mobile-telefony-i-garnitury', 'Смартфони та мобільні телефони', 'mobile-telefony-i-garnitury', 'Смартфони та мобільні телефони', 'https://hotline.ua/ua/mobile/telefony-i-garnitury/', 'mobile', 'Смартфони, Смарт-годинники', 2010),
    HotlineSeedTemplate('mobile-umnye-chasy-smartwatch', 'Смарт-годинники і фітнес-браслети', 'mobile-umnye-chasy-smartwatch', 'Смарт-годинники і фітнес-браслети', 'https://hotline.ua/ua/mobile/umnye-chasy-smartwatch/', 'mobile', 'Смартфони, Смарт-годинники', 2020),
    HotlineSeedTemplate('mobile-naushniki-garnitury', 'Навушники', 'mobile-naushniki-garnitury', 'Навушники', 'https://hotline.ua/ua/av/naushniki-garnitury/', 'mobile', 'Смартфони, Смарт-годинники', 2030),
    HotlineSeedTemplate('mobile-zaryadka-i-sinhronizaciya', 'Живлення', 'mobile-zaryadka-i-sinhronizaciya', 'Живлення', 'https://hotline.ua/ua/mobile/zaryadka-i-sinhronizaciya/', 'mobile', 'Смартфони, Смарт-годинники', 2040),
    HotlineSeedTemplate('mobile-aksessuary-dlya-zaryadki', 'Аксесуари для заряджання', 'mobile-aksessuary-dlya-zaryadki', 'Аксесуари для заряджання', 'https://hotline.ua/ua/mobile/aksessuary-dlya-zaryadki/', 'mobile', 'Смартфони, Смарт-годинники', 2050),
    HotlineSeedTemplate('mobile-chokhly-ta-zakhysni-plivky', 'Чохли для смартфонів', 'mobile-chokhly-ta-zakhysni-plivky', 'Чохли для смартфонів', 'https://hotline.ua/ua/mobile/chokhly-ta-zakhysni-plivky/', 'mobile', 'Смартфони, Смарт-годинники', 2060),
    HotlineSeedTemplate('mobile-dopolnitelnoe-oborudovanie-i-aksessuary', 'Аксесуари', 'mobile-dopolnitelnoe-oborudovanie-i-aksessuary', 'Аксесуари', 'https://hotline.ua/ua/mobile/dopolnitelnoe-oborudovanie-i-aksessuary/', 'mobile', 'Смартфони, Смарт-годинники', 2070),
    HotlineSeedTemplate('computer-noutbuki-pk', 'Ноутбуки, планшети, електронні книги', 'computer-noutbuki-pk', 'Ноутбуки, планшети, електронні книги', 'https://hotline.ua/ua/computer/noutbuki-pk/', 'computer', "Комп'ютери, Мережі", 3010),
    HotlineSeedTemplate('computer-setevoe-oborudovanie', 'Мережі, інтернет', 'computer-setevoe-oborudovanie', 'Мережі, інтернет', 'https://hotline.ua/ua/computer/setevoe-oborudovanie/', 'computer', "Комп'ютери, Мережі", 3020),
    HotlineSeedTemplate('computer-sredstva-multimedia', 'Товари для геймерів', 'computer-sredstva-multimedia', 'Товари для геймерів', 'https://hotline.ua/ua/computer/sredstva-multimedia/', 'computer', "Комп'ютери, Мережі", 3030),
    HotlineSeedTemplate('computer-nastolnye-pk-monitory', "Комп'ютери, монітори, сервери", 'computer-nastolnye-pk-monitory', "Комп'ютери, монітори, сервери", 'https://hotline.ua/ua/computer/nastolnye-pk-monitory/', 'computer', "Комп'ютери, Мережі", 3040),
    HotlineSeedTemplate('computer-elektropitanie', 'Електроживлення', 'computer-elektropitanie', 'Електроживлення', 'https://hotline.ua/ua/computer/elektropitanie/', 'computer', "Комп'ютери, Мережі", 3050),
    HotlineSeedTemplate('computer-kompyuternaya-periferiya', "Комп'ютерна периферія", 'computer-kompyuternaya-periferiya', "Комп'ютерна периферія", 'https://hotline.ua/ua/computer/kompyuternaya-periferiya/', 'computer', "Комп'ютери, Мережі", 3060),
    HotlineSeedTemplate('computer-komplektuyuschie-dlya-pk', 'Комплектуючі', 'computer-komplektuyuschie-dlya-pk', 'Комплектуючі', 'https://hotline.ua/ua/computer/komplektuyuschie-dlya-pk/', 'computer', "Комп'ютери, Мережі", 3070),
    HotlineSeedTemplate('computer-printery-mfu-plottery', 'Принтери, БФП', 'computer-printery-mfu-plottery', 'Принтери, БФП', 'https://hotline.ua/ua/computer/printery-mfu-plottery/', 'computer', "Комп'ютери, Мережі", 3080),
    HotlineSeedTemplate('computer-programmnoe-obespechenie', 'Програмне забезпечення', 'computer-programmnoe-obespechenie', 'Програмне забезпечення', 'https://hotline.ua/ua/computer/programmnoe-obespechenie/', 'computer', "Комп'ютери, Мережі", 3090),
    HotlineSeedTemplate('bt-krupnaya-bytovaya-tehnika', 'Велика побутова техніка', 'bt-krupnaya-bytovaya-tehnika', 'Велика побутова техніка', 'https://hotline.ua/ua/bt/krupnaya-bytovaya-tehnika/', 'bt', 'Побутова техніка', 4010),
    HotlineSeedTemplate('bt-vstraivaemaya-tehnika', 'Вбудована техніка', 'bt-vstraivaemaya-tehnika', 'Вбудована техніка', 'https://hotline.ua/ua/bt/vstraivaemaya-tehnika/', 'bt', 'Побутова техніка', 4020),
    HotlineSeedTemplate('bt-klimaticheskaya-tehnika', 'Кліматична техніка', 'bt-klimaticheskaya-tehnika', 'Кліматична техніка', 'https://hotline.ua/ua/bt/klimaticheskaya-tehnika/', 'bt', 'Побутова техніка', 4030),
    HotlineSeedTemplate('bt-tehnika-dlya-doma', 'Техніка для дому', 'bt-tehnika-dlya-doma', 'Техніка для дому', 'https://hotline.ua/ua/bt/tehnika-dlya-doma/', 'bt', 'Побутова техніка', 4040),
    HotlineSeedTemplate('bt-personalnyi-dogliad', 'Персональний догляд', 'bt-personalnyi-dogliad', 'Персональний догляд', 'https://hotline.ua/ua/bt/personalnyi-dogliad/', 'bt', 'Побутова техніка', 4050),
    HotlineSeedTemplate('bt-melkaya-tehnika-dlya-kuhni', 'Техніка для кухні', 'bt-melkaya-tehnika-dlya-kuhni', 'Техніка для кухні', 'https://hotline.ua/ua/bt/melkaya-tehnika-dlya-kuhni/', 'bt', 'Побутова техніка', 4060),
    HotlineSeedTemplate('bt-smart-technika', 'Смарт техніка', 'bt-smart-technika', 'Смарт техніка', 'https://hotline.ua/ua/bt/smart-technika/', 'bt', 'Побутова техніка', 4070),
    HotlineSeedTemplate('av-televizory', 'Телевізори', 'av-televizory', 'Телевізори', 'https://hotline.ua/ua/av/televizory/', 'av', 'ТВ, Аудіо, Відео, Фото', 5010),
    HotlineSeedTemplate('av-televizory-proektory', 'Все для телевізорів', 'av-televizory-proektory', 'Все для телевізорів', 'https://hotline.ua/ua/av/televizory-proektory/', 'av', 'ТВ, Аудіо, Відео, Фото', 5020),
    HotlineSeedTemplate('av-projectors', 'Проекційне обладнання', 'av-projectors', 'Проекційне обладнання', 'https://hotline.ua/ua/av/projectors/', 'av', 'ТВ, Аудіо, Відео, Фото', 5030),
    HotlineSeedTemplate('av-naushniki-garnitury', 'Навушники', 'av-naushniki-garnitury', 'Навушники', 'https://hotline.ua/ua/av/naushniki-garnitury/', 'av', 'ТВ, Аудіо, Відео, Фото', 5040),
    HotlineSeedTemplate('av-audio', 'Аудіо техніка', 'av-audio', 'Аудіо техніка', 'https://hotline.ua/ua/av/audio/', 'av', 'ТВ, Аудіо, Відео, Фото', 5050),
    HotlineSeedTemplate('av-videokamery-i-videooborudovanie', 'Екстремальна відеозйомка', 'av-videokamery-i-videooborudovanie', 'Екстремальна відеозйомка', 'https://hotline.ua/ua/av/videokamery-i-videooborudovanie/', 'av', 'ТВ, Аудіо, Відео, Фото', 5060),
    HotlineSeedTemplate('av-fotoapparaty-obektivy', 'Фото та відео техніка', 'av-fotoapparaty-obektivy', 'Фото та відео техніка', 'https://hotline.ua/ua/av/fotoapparaty-obektivy/', 'av', 'ТВ, Аудіо, Відео, Фото', 5070),
    HotlineSeedTemplate('game-game-zone', 'Товари для геймерів', 'game-game-zone', 'Товари для геймерів', 'https://hotline.ua/ua/game/game-zone/', 'game', 'Товари для геймерів', 6010),
    HotlineSeedTemplate('game-ihrovi-aksesuary', 'Контролери і аксесуари', 'game-ihrovi-aksesuary', 'Контролери і аксесуари', 'https://hotline.ua/ua/game/ihrovi-aksesuary/', 'game', 'Товари для геймерів', 6020),
    HotlineSeedTemplate('auto-shiny-i-diski', 'Шини і диски', 'auto-shiny-i-diski', 'Шини і диски', 'https://hotline.ua/ua/auto/shiny-i-diski/', 'auto', 'Авто і Мото', 7010),
    HotlineSeedTemplate('auto-akkumulyatory', 'Автомобільні акумулятори', 'auto-akkumulyatory', 'Автомобільні акумулятори', 'https://hotline.ua/ua/auto/akkumulyatory/', 'auto', 'Авто і Мото', 7020),
    HotlineSeedTemplate('auto-avtomobilnoe-audio-i-video', 'Автозвук, відео, навігація', 'auto-avtomobilnoe-audio-i-video', 'Автозвук, відео, навігація', 'https://hotline.ua/ua/auto/avtomobilnoe-audio-i-video/', 'auto', 'Авто і Мото', 7030),
    HotlineSeedTemplate('auto-avto-svet', 'Автосвітло', 'auto-avto-svet', 'Автосвітло', 'https://hotline.ua/ua/auto/avto-svet/', 'auto', 'Авто і Мото', 7040),
    HotlineSeedTemplate('auto-avtooborudovanie', 'Салон', 'auto-avtooborudovanie', 'Салон', 'https://hotline.ua/ua/auto/avtooborudovanie/', 'auto', 'Авто і Мото', 7050),
    HotlineSeedTemplate('auto-avtohimiya', 'Автохімія, мастила', 'auto-avtohimiya', 'Автохімія, мастила', 'https://hotline.ua/ua/auto/avtohimiya/', 'auto', 'Авто і Мото', 7060),
    HotlineSeedTemplate('auto-tehpomosch', 'Техдопомога', 'auto-tehpomosch', 'Техдопомога', 'https://hotline.ua/ua/auto/tehpomosch/', 'auto', 'Авто і Мото', 7070),
    HotlineSeedTemplate('auto-avtoelektronika', 'Автоелектрика і електроніка', 'auto-avtoelektronika', 'Автоелектрика і електроніка', 'https://hotline.ua/ua/auto/avtoelektronika/', 'auto', 'Авто і Мото', 7080),
    HotlineSeedTemplate('auto-moto', 'Мотоцикли, скутери', 'auto-moto', 'Мотоцикли, скутери', 'https://hotline.ua/ua/auto/moto/', 'auto', 'Авто і Мото', 7090),
    HotlineSeedTemplate('dom-mebel', 'Меблі', 'dom-mebel', 'Меблі', 'https://hotline.ua/ua/dom/mebel/', 'dom', 'Все для дому', 8010),
    HotlineSeedTemplate('dom-domashnij-tekstil', 'Домашній текстиль', 'dom-domashnij-tekstil', 'Домашній текстиль', 'https://hotline.ua/ua/dom/domashnij-tekstil/', 'dom', 'Все для дому', 8020),
    HotlineSeedTemplate('dom-produkty-napitki-alkogol', 'Кава, чай, алкоголь', 'dom-produkty-napitki-alkogol', 'Кава, чай, алкоголь', 'https://hotline.ua/ua/dom/produkty-napitki-alkogol/', 'dom', 'Все для дому', 8030),
    HotlineSeedTemplate('dom-posuda', 'Посуд', 'dom-posuda', 'Посуд', 'https://hotline.ua/ua/dom/posuda/', 'dom', 'Все для дому', 8040),
    HotlineSeedTemplate('dom-bytovaya-himiyapoint-hoztovary', 'Побутова хімія, господарські товари', 'dom-bytovaya-himiyapoint-hoztovary', 'Побутова хімія, господарські товари', 'https://hotline.ua/ua/dom/bytovaya-himiyapoint-hoztovary/', 'dom', 'Все для дому', 8050),
    HotlineSeedTemplate('dom-umnyj-dom', 'Розумний будинок', 'dom-umnyj-dom', 'Розумний будинок', 'https://hotline.ua/ua/dom/umnyj--dom/', 'dom', 'Все для дому', 8060),
    HotlineSeedTemplate('dom-osveschenie-electrica', 'Освітлення, електрика', 'dom-osveschenie-electrica', 'Освітлення, електрика', 'https://hotline.ua/ua/dom/osveschenie-electrica/', 'dom', 'Все для дому', 8070),
    HotlineSeedTemplate('dom-novogodnie-tovary', 'Новорічні товари', 'dom-novogodnie-tovary', 'Новорічні товари', 'https://hotline.ua/ua/dom/novogodnie-tovary/', 'dom', 'Все для дому', 8080),
    HotlineSeedTemplate('dom-interer', "Інтер'єр", 'dom-interer', "Інтер'єр", 'https://hotline.ua/ua/dom/interer/', 'dom', 'Все для дому', 8090),
    HotlineSeedTemplate('dacha-sad-sadovaya-tehnika', 'Садова техніка', 'dacha-sad-sadovaya-tehnika', 'Садова техніка', 'https://hotline.ua/ua/dacha_sad/sadovaya-tehnika/', 'dacha_sad', 'Дача, сад', 9010),
    HotlineSeedTemplate('dacha-sad-dachnoe-elektropitanie', 'Альтернативні джерела енергії', 'dacha-sad-dachnoe-elektropitanie', 'Альтернативні джерела енергії', 'https://hotline.ua/ua/dacha_sad/dachnoe-elektropitanie/', 'dacha_sad', 'Дача, сад', 9020),
    HotlineSeedTemplate('dacha-sad-otopleniepoint-vodonagrevateli', 'Опалення, водонагрівачі', 'dacha-sad-otopleniepoint-vodonagrevateli', 'Опалення, водонагрівачі', 'https://hotline.ua/ua/dacha_sad/otopleniepoint-vodonagrevateli/', 'dacha_sad', 'Дача, сад', 9030),
    HotlineSeedTemplate('dacha-sad-vodosnabzheniepoint-polivpoint-kanalizaciya', 'Водопостачання, полив', 'dacha-sad-vodosnabzheniepoint-polivpoint-kanalizaciya', 'Водопостачання, полив', 'https://hotline.ua/ua/dacha_sad/vodosnabzheniepoint-polivpoint-kanalizaciya/', 'dacha_sad', 'Дача, сад', 9040),
    HotlineSeedTemplate('dacha-sad-sadovaya-mebelpoint-interer', 'Садові меблі, декор', 'dacha-sad-sadovaya-mebelpoint-interer', 'Садові меблі, декор', 'https://hotline.ua/ua/dacha_sad/sadovaya-mebelpoint-interer/', 'dacha_sad', 'Дача, сад', 9050),
    HotlineSeedTemplate('dacha-sad-sadovodstvo-fermerstvo', 'Садівництво, фермерство', 'dacha-sad-sadovodstvo-fermerstvo', 'Садівництво, фермерство', 'https://hotline.ua/ua/dacha_sad/sadovodstvo-fermerstvo/', 'dacha_sad', 'Дача, сад', 9060),
    HotlineSeedTemplate('dacha-sad-ruchnoj-sadovyj-instrument', 'Ручний садовий інструмент', 'dacha-sad-ruchnoj-sadovyj-instrument', 'Ручний садовий інструмент', 'https://hotline.ua/ua/dacha_sad/ruchnoj-sadovyj-instrument/', 'dacha_sad', 'Дача, сад', 9070),
    HotlineSeedTemplate('dacha-sad-internet-i-televidenie', 'Інтернет і телебачення', 'dacha-sad-internet-i-televidenie', 'Інтернет і телебачення', 'https://hotline.ua/ua/dacha_sad/internet-i-televidenie/', 'dacha_sad', 'Дача, сад', 9080),
    HotlineSeedTemplate('dacha-sad-populyarno-seychas-dacha-sad', 'Популярно зараз', 'dacha-sad-populyarno-seychas-dacha-sad', 'Популярно зараз', 'https://hotline.ua/ua/dacha_sad/populyarno-seychas-dacha_sad/', 'dacha_sad', 'Дача, сад', 9090),
    HotlineSeedTemplate('deti-konstruktory-lego', 'LEGO', 'deti-konstruktory-lego', 'LEGO', 'https://hotline.ua/ua/deti/konstruktory-lego/', 'deti', 'Дитячі товари', 10010),
    HotlineSeedTemplate('deti-detskie-igrushki', 'Іграшки та розваги', 'deti-detskie-igrushki', 'Іграшки та розваги', 'https://hotline.ua/ua/deti/detskie-igrushki/', 'deti', 'Дитячі товари', 10020),
    HotlineSeedTemplate('deti-kolyaski-i-avtokresla', 'Автокрісла', 'deti-kolyaski-i-avtokresla', 'Автокрісла', 'https://hotline.ua/ua/deti/kolyaski-i-avtokresla/', 'deti', 'Дитячі товари', 10030),
    HotlineSeedTemplate('deti-koliasky', 'Коляски', 'deti-koliasky', 'Коляски', 'https://hotline.ua/ua/deti/koliasky/', 'deti', 'Дитячі товари', 10040),
    HotlineSeedTemplate('deti-dlya-malyshej', 'Догляд за малюком', 'deti-dlya-malyshej', 'Догляд за малюком', 'https://hotline.ua/ua/deti/dlya-malyshej/', 'deti', 'Дитячі товари', 10050),
    HotlineSeedTemplate('deti-detskaya-mebel', 'Меблі та обстановка', 'deti-detskaya-mebel', 'Меблі та обстановка', 'https://hotline.ua/ua/deti/detskaya-mebel/', 'deti', 'Дитячі товари', 10060),
    HotlineSeedTemplate('deti-tovary-dlya-shkoly', 'Навчання та школа', 'deti-tovary-dlya-shkoly', 'Навчання та школа', 'https://hotline.ua/ua/deti/tovary-dlya-shkoly/', 'deti', 'Дитячі товари', 10070),
    HotlineSeedTemplate('deti-detskij-transport', 'Активний відпочинок та спорт', 'deti-detskij-transport', 'Активний відпочинок та спорт', 'https://hotline.ua/ua/deti/detskij-transport/', 'deti', 'Дитячі товари', 10080),
    HotlineSeedTemplate('constructors-lego-age-lego', 'Вік', 'constructors-lego-age-lego', 'Вік', 'https://hotline.ua/ua/constructors-lego/age-lego/', 'constructors-lego', 'LEGO', 11010),
    HotlineSeedTemplate('constructors-lego-themes-lego', 'Серії', 'constructors-lego-themes-lego', 'Серії', 'https://hotline.ua/ua/constructors-lego/themes-lego/', 'constructors-lego', 'LEGO', 11020),
    HotlineSeedTemplate('constructors-lego-categories-lego', 'Інтереси', 'constructors-lego-categories-lego', 'Інтереси', 'https://hotline.ua/ua/constructors-lego/categories-lego/', 'constructors-lego', 'LEGO', 11030),
    HotlineSeedTemplate('military-tekhnycheskoe-snariazhenye', 'Тактичне технічне спорядження', 'military-tekhnycheskoe-snariazhenye', 'Тактичне технічне спорядження', 'https://hotline.ua/ua/military/tekhnycheskoe-snariazhenye/', 'military', 'Для військових', 12010),
    HotlineSeedTemplate('military-taktichniy-odyag', 'Тактичний одяг та обладнання', 'military-taktichniy-odyag', 'Тактичний одяг та обладнання', 'https://hotline.ua/ua/military/taktichniy-odyag/', 'military', 'Для військових', 12020),
    HotlineSeedTemplate('military-amunytsyia', 'Для місця розташування', 'military-amunytsyia', 'Для місця розташування', 'https://hotline.ua/ua/military/amunytsyia/', 'military', 'Для військових', 12030),
    HotlineSeedTemplate('military-pokhodnoe-snariazhenye', "Особиста гігієна та здоров'я", 'military-pokhodnoe-snariazhenye', "Особиста гігієна та здоров'я", 'https://hotline.ua/ua/military/pokhodnoe-snariazhenye/', 'military', 'Для військових', 12040),
    HotlineSeedTemplate('military-zdorove-hyhyena', 'Для транспорту', 'military-zdorove-hyhyena', 'Для транспорту', 'https://hotline.ua/ua/military/zdorove-hyhyena/', 'military', 'Для військових', 12050),
    HotlineSeedTemplate('zootovary-dlya-koshek', 'Для котів', 'zootovary-dlya-koshek', 'Для котів', 'https://hotline.ua/ua/zootovary/dlya-koshek/', 'zootovary', 'Зоотовари', 13010),
    HotlineSeedTemplate('zootovary-sobakam', 'Для собак', 'zootovary-sobakam', 'Для собак', 'https://hotline.ua/ua/zootovary/sobakam/', 'zootovary', 'Зоотовари', 13020),
    HotlineSeedTemplate('zootovary-dlya-ryb-i-reptilij', 'Акваріумістика', 'zootovary-dlya-ryb-i-reptilij', 'Акваріумістика', 'https://hotline.ua/ua/zootovary/dlya-ryb-i-reptilij/', 'zootovary', 'Зоотовари', 13030),
    HotlineSeedTemplate('tools-sverlilnyj-elektroinstrument', 'Свердлильний електроінструмент', 'tools-sverlilnyj-elektroinstrument', 'Свердлильний електроінструмент', 'https://hotline.ua/ua/tools/sverlilnyj-elektroinstrument/', 'tools', 'Інструменти', 14010),
    HotlineSeedTemplate('tools-svarochnoe-oborudovanie', 'Зварювальне обладнання', 'tools-svarochnoe-oborudovanie', 'Зварювальне обладнання', 'https://hotline.ua/ua/tools/svarochnoe-oborudovanie/', 'tools', 'Інструменти', 14020),
    HotlineSeedTemplate('tools-shlifovalnyjpoint-otreznoj-elektroinstrument', 'Шліфувальний, відрізний електроінструмент', 'tools-shlifovalnyjpoint-otreznoj-elektroinstrument', 'Шліфувальний, відрізний електроінструмент', 'https://hotline.ua/ua/tools/shlifovalnyjpoint-otreznoj-elektroinstrument/', 'tools', 'Інструменти', 14030),
    HotlineSeedTemplate('tools-malyarnyj-instrument', 'Малярський інструмент', 'tools-malyarnyj-instrument', 'Малярський інструмент', 'https://hotline.ua/ua/tools/malyarnyj-instrument/', 'tools', 'Інструменти', 14040),
    HotlineSeedTemplate('tools-stroitelnoe-oborudovanie', 'Будівельне обладнання', 'tools-stroitelnoe-oborudovanie', 'Будівельне обладнання', 'https://hotline.ua/ua/tools/stroitelnoe-oborudovanie/', 'tools', 'Інструменти', 14050),
    HotlineSeedTemplate('tools-izmeritelnyj-instrument', 'Вимірювальний інструмент', 'tools-izmeritelnyj-instrument', 'Вимірювальний інструмент', 'https://hotline.ua/ua/tools/izmeritelnyj-instrument/', 'tools', 'Інструменти', 14060),
    HotlineSeedTemplate('tools-elektroinstrument', 'Спеціалізований електроінструмент', 'tools-elektroinstrument', 'Спеціалізований електроінструмент', 'https://hotline.ua/ua/tools/elektroinstrument/', 'tools', 'Інструменти', 14070),
    HotlineSeedTemplate('tools-ruchnoj-instrument', 'Слюсарний інструмент, ключі', 'tools-ruchnoj-instrument', 'Слюсарний інструмент, ключі', 'https://hotline.ua/ua/tools/ruchnoj-instrument/', 'tools', 'Інструменти', 14080),
    HotlineSeedTemplate('tools-stanki', 'Верстати', 'tools-stanki', 'Верстати', 'https://hotline.ua/ua/tools/stanki/', 'tools', 'Інструменти', 14090),
    HotlineSeedTemplate('tools-stolyarnyj-instrument', 'Столярний інструмент', 'tools-stolyarnyj-instrument', 'Столярний інструмент', 'https://hotline.ua/ua/tools/stolyarnyj-instrument/', 'tools', 'Інструменти', 14100),
    HotlineSeedTemplate('tools-populyarno-seychas-tools', 'Популярно зараз', 'tools-populyarno-seychas-tools', 'Популярно зараз', 'https://hotline.ua/ua/tools/populyarno-seychas-tools/', 'tools', 'Інструменти', 14110),
    HotlineSeedTemplate('krasota-uhod-za-telom', 'Косметика по догляду', 'krasota-uhod-za-telom', 'Косметика по догляду', 'https://hotline.ua/ua/krasota/uhod-za-telom/', 'krasota', "Краса і здоров'я", 15010),
    HotlineSeedTemplate('krasota-tovary-medicinskogo-naznacheniya', 'Захист від вірусів', 'krasota-tovary-medicinskogo-naznacheniya', 'Захист від вірусів', 'https://hotline.ua/ua/krasota/tovary-medicinskogo-naznacheniya/', 'krasota', "Краса і здоров'я", 15020),
    HotlineSeedTemplate('krasota-bytovye-medicinskie-pribory', 'Медтехніка для дому', 'krasota-bytovye-medicinskie-pribory', 'Медтехніка для дому', 'https://hotline.ua/ua/krasota/bytovye-medicinskie-pribory/', 'krasota', "Краса і здоров'я", 15030),
    HotlineSeedTemplate('krasota-tovary-dlya-krasoty-i-personalnogo-uhoda', 'Техніка для краси і догляду', 'krasota-tovary-dlya-krasoty-i-personalnogo-uhoda', 'Техніка для краси і догляду', 'https://hotline.ua/ua/krasota/tovary-dlya-krasoty-i-personalnogo-uhoda/', 'krasota', "Краса і здоров'я", 15040),
    HotlineSeedTemplate('krasota-parfyumeriya', 'Парфумерія', 'krasota-parfyumeriya', 'Парфумерія', 'https://hotline.ua/ua/krasota/parfyumeriya/', 'krasota', "Краса і здоров'я", 15050),
    HotlineSeedTemplate('krasota-uhod-i-reabilitaciya', 'Догляд та реабілітація на дому', 'krasota-uhod-i-reabilitaciya', 'Догляд та реабілітація на дому', 'https://hotline.ua/ua/krasota/uhod-i-reabilitaciya/', 'krasota', "Краса і здоров'я", 15060),
    HotlineSeedTemplate('krasota-kontaktnye-linzypoint-ochki', 'Товари для персонального догляду', 'krasota-kontaktnye-linzypoint-ochki', 'Товари для персонального догляду', 'https://hotline.ua/ua/krasota/kontaktnye-linzypoint-ochki/', 'krasota', "Краса і здоров'я", 15070),
    HotlineSeedTemplate('musical-instruments-gitary', 'Гітари', 'musical-instruments-gitary', 'Гітари', 'https://hotline.ua/ua/musical_instruments/gitary/', 'musical_instruments', 'Музичні інструменти', 16010),
    HotlineSeedTemplate('musical-instruments-klavishnye-instrumenty', 'Клавішні інструменти', 'musical-instruments-klavishnye-instrumenty', 'Клавішні інструменти', 'https://hotline.ua/ua/musical_instruments/klavishnye-instrumenty/', 'musical_instruments', 'Музичні інструменти', 16020),
    HotlineSeedTemplate('musical-instruments-smychkovye-instrumenty', 'Смичкові інструменти', 'musical-instruments-smychkovye-instrumenty', 'Смичкові інструменти', 'https://hotline.ua/ua/musical_instruments/smychkovye-instrumenty/', 'musical_instruments', 'Музичні інструменти', 16030),
    HotlineSeedTemplate('musical-instruments-etnicheskie-instrumenty', 'Етнічні струнні інструменти', 'musical-instruments-etnicheskie-instrumenty', 'Етнічні струнні інструменти', 'https://hotline.ua/ua/musical_instruments/etnicheskie-instrumenty/', 'musical_instruments', 'Музичні інструменти', 16040),
    HotlineSeedTemplate('musical-instruments-udarnye-instrumenty', 'Ударні інструменти', 'musical-instruments-udarnye-instrumenty', 'Ударні інструменти', 'https://hotline.ua/ua/musical_instruments/udarnye-instrumenty/', 'musical_instruments', 'Музичні інструменти', 16050),
    HotlineSeedTemplate('musical-instruments-duhovye-instrumenty', 'Духові інструменти', 'musical-instruments-duhovye-instrumenty', 'Духові інструменти', 'https://hotline.ua/ua/musical_instruments/duhovye-instrumenty/', 'musical_instruments', 'Музичні інструменти', 16060),
    HotlineSeedTemplate('musical-instruments-muzykalnoe-oborudovanie', 'Музичне обладнання', 'musical-instruments-muzykalnoe-oborudovanie', 'Музичне обладнання', 'https://hotline.ua/ua/musical_instruments/muzykalnoe-oborudovanie/', 'musical_instruments', 'Музичні інструменти', 16070),
    HotlineSeedTemplate('pobutova-himiia-sredstva-dlya-stirki', 'Засоби для прання', 'pobutova-himiia-sredstva-dlya-stirki', 'Засоби для прання', 'https://hotline.ua/ua/pobutova_himiia/sredstva-dlya-stirki/', 'pobutova_himiia', 'Побутова хімія', 17010),
    HotlineSeedTemplate('pobutova-himiia-sredstva-dlya-mytya-posudy', 'Засоби для миття посуду', 'pobutova-himiia-sredstva-dlya-mytya-posudy', 'Засоби для миття посуду', 'https://hotline.ua/ua/pobutova_himiia/sredstva-dlya-mytya-posudy/', 'pobutova_himiia', 'Побутова хімія', 17020),
    HotlineSeedTemplate('pobutova-himiia-sredstva-po-uhodu-za-bytovoj-tehnikoj', 'Засоби по догляду за побутовою технікою', 'pobutova-himiia-sredstva-po-uhodu-za-bytovoj-tehnikoj', 'Засоби по догляду за побутовою технікою', 'https://hotline.ua/ua/pobutova_himiia/sredstva-po-uhodu-za-bytovoj-tehnikoj/', 'pobutova_himiia', 'Побутова хімія', 17030),
    HotlineSeedTemplate('pobutova-himiia-zasoby-dlia-prybyrannia', 'Засоби для прибирання', 'pobutova-himiia-zasoby-dlia-prybyrannia', 'Засоби для прибирання', 'https://hotline.ua/ua/pobutova_himiia/zasoby-dlia-prybyrannia/', 'pobutova_himiia', 'Побутова хімія', 17040),
    HotlineSeedTemplate('pobutova-himiia-zasoby-dohliadu-za-santekhnikoiu', 'Засоби для догляду за сантехнікою', 'pobutova-himiia-zasoby-dohliadu-za-santekhnikoiu', 'Засоби для догляду за сантехнікою', 'https://hotline.ua/ua/pobutova_himiia/zasoby-dohliadu-za-santekhnikoiu/', 'pobutova_himiia', 'Побутова хімія', 17050),
    HotlineSeedTemplate('pobutova-himiia-hoztovary', 'Господарські товари', 'pobutova-himiia-hoztovary', 'Господарські товари', 'https://hotline.ua/ua/pobutova_himiia/hoztovary/', 'pobutova_himiia', 'Побутова хімія', 17060),
    HotlineSeedTemplate('pobutova-himiia-vulychna-zona', 'Вулична зона', 'pobutova-himiia-vulychna-zona', 'Вулична зона', 'https://hotline.ua/ua/pobutova_himiia/vulychna-zona/', 'pobutova_himiia', 'Побутова хімія', 17070),
    HotlineSeedTemplate('pobutova-himiia-zasoby-dohliadu-za-vzuttiam', 'Засоби для догляду за взуттям', 'pobutova-himiia-zasoby-dohliadu-za-vzuttiam', 'Засоби для догляду за взуттям', 'https://hotline.ua/ua/pobutova_himiia/zasoby-dohliadu-za-vzuttiam/', 'pobutova_himiia', 'Побутова хімія', 17080),
    HotlineSeedTemplate('remont-vodonagrevateli-otoplenie', 'Водонагрівачі, опалення', 'remont-vodonagrevateli-otoplenie', 'Водонагрівачі, опалення', 'https://hotline.ua/ua/remont/vodonagrevateli-otoplenie/', 'remont', 'Сантехніка, Будматеріали', 18010),
    HotlineSeedTemplate('remont-polypoint-oknapoint-dveri', 'Підлоги, двері', 'remont-polypoint-oknapoint-dveri', 'Підлоги, двері', 'https://hotline.ua/ua/remont/polypoint-oknapoint-dveri/', 'remont', 'Сантехніка, Будматеріали', 18020),
    HotlineSeedTemplate('remont-elektrika', 'Електрика, освітлення', 'remont-elektrika', 'Електрика, освітлення', 'https://hotline.ua/ua/remont/elektrika/', 'remont', 'Сантехніка, Будматеріали', 18030),
    HotlineSeedTemplate('remont-santehnika', 'Сантехніка', 'remont-santehnika', 'Сантехніка', 'https://hotline.ua/ua/remont/santehnika/', 'remont', 'Сантехніка, Будматеріали', 18040),
    HotlineSeedTemplate('remont-otdelochnye-materialy', 'Оздоблювальні матеріали', 'remont-otdelochnye-materialy', 'Оздоблювальні матеріали', 'https://hotline.ua/ua/remont/otdelochnye-materialy/', 'remont', 'Сантехніка, Будматеріали', 18050),
    HotlineSeedTemplate('remont-mebel-i-aksessuary-dlya-vannoj-komnaty', 'Меблі та аксесуари для ванної кімнати', 'remont-mebel-i-aksessuary-dlya-vannoj-komnaty', 'Меблі та аксесуари для ванної кімнати', 'https://hotline.ua/ua/remont/mebel-i-aksessuary-dlya-vannoj-komnaty/', 'remont', 'Сантехніка, Будматеріали', 18060),
    HotlineSeedTemplate('remont-stroitelnye-smesipoint-klei', 'Будівельні суміші, клеї', 'remont-stroitelnye-smesipoint-klei', 'Будівельні суміші, клеї', 'https://hotline.ua/ua/remont/stroitelnye-smesipoint-klei/', 'remont', 'Сантехніка, Будматеріали', 18070),
    HotlineSeedTemplate('remont-populyarno-seychas-remont', 'Популярно зараз', 'remont-populyarno-seychas-remont', 'Популярно зараз', 'https://hotline.ua/ua/remont/populyarno-seychas-remont/', 'remont', 'Сантехніка, Будматеріали', 18080),
    HotlineSeedTemplate('sport-sportivne', 'Спорт', 'sport-sportivne', 'Спорт', 'https://hotline.ua/ua/sport/sportivne/', 'sport', 'Спорт, Активний відпочинок', 19010),
    HotlineSeedTemplate('sport-fitnes', 'Йога, фітнес', 'sport-fitnes', 'Йога, фітнес', 'https://hotline.ua/ua/sport/fitnes/', 'sport', 'Спорт, Активний відпочинок', 19020),
    HotlineSeedTemplate('sport-transport', 'Транспорт, електротранспорт', 'sport-transport', 'Транспорт, електротранспорт', 'https://hotline.ua/ua/sport/transport/', 'sport', 'Спорт, Активний відпочинок', 19030),
    HotlineSeedTemplate('sport-turizm-kemping-plyazh', 'Туризм, кемпінг', 'sport-turizm-kemping-plyazh', 'Туризм, кемпінг', 'https://hotline.ua/ua/sport/turizm-kemping-plyazh/', 'sport', 'Спорт, Активний відпочинок', 19040),
    HotlineSeedTemplate('sport-pnevmatika', 'Пневматика та спорядження', 'sport-pnevmatika', 'Пневматика та спорядження', 'https://hotline.ua/ua/sport/pnevmatika/', 'sport', 'Спорт, Активний відпочинок', 19050),
    HotlineSeedTemplate('sport-aktyvnyi-vidpochynok', 'Активний відпочинок', 'sport-aktyvnyi-vidpochynok', 'Активний відпочинок', 'https://hotline.ua/ua/sport/aktyvnyi-vidpochynok/', 'sport', 'Спорт, Активний відпочинок', 19060),
    HotlineSeedTemplate('sport-rybalka', 'Риболовля', 'sport-rybalka', 'Риболовля', 'https://hotline.ua/ua/sport/rybalka/', 'sport', 'Спорт, Активний відпочинок', 19070),
    HotlineSeedTemplate('sport-sportivnaya-odezhdapoint-obuv', 'Одяг, взуття', 'sport-sportivnaya-odezhdapoint-obuv', 'Одяг, взуття', 'https://hotline.ua/ua/sport/sportivnaya-odezhdapoint-obuv/', 'sport', 'Спорт, Активний відпочинок', 19080),
    HotlineSeedTemplate('sport-bagazh', 'Багаж', 'sport-bagazh', 'Багаж', 'https://hotline.ua/ua/sport/bagazh/', 'sport', 'Спорт, Активний відпочинок', 19090),
    HotlineSeedTemplate('adult-intim', 'Інтим', 'adult-intim', 'Інтим', 'https://hotline.ua/ua/adult/intim/', 'adult', 'Товари для дорослих', 20010),
    HotlineSeedTemplate('adult-eroticheskaya-odezhda', 'Еротичний одяг, ігри', 'adult-eroticheskaya-odezhda', 'Еротичний одяг, ігри', 'https://hotline.ua/ua/adult/eroticheskaya-odezhda/', 'adult', 'Товари для дорослих', 20020),
    HotlineSeedTemplate('adult-napitki-alkogol', 'Алкоголь', 'adult-napitki-alkogol', 'Алкоголь', 'https://hotline.ua/ua/adult/napitki-alkogol/', 'adult', 'Товари для дорослих', 20030),
    HotlineSeedTemplate('fashion-naruchnye-chasy', 'Наручні годинники', 'fashion-naruchnye-chasy', 'Наручні годинники', 'https://hotline.ua/ua/fashion/naruchnye-chasy/', 'fashion', 'Годинники, Сумки, Аксесуари', 21010),
    HotlineSeedTemplate('fashion-umnye-chasy-smartwatch', 'Смарт-годинники', 'fashion-umnye-chasy-smartwatch', 'Смарт-годинники', 'https://hotline.ua/ua/mobile/umnye-chasy-smartwatch/', 'fashion', 'Годинники, Сумки, Аксесуари', 21020),
    HotlineSeedTemplate('fashion-sumki-i-aksessuary', 'Сумки, аксесуари', 'fashion-sumki-i-aksessuary', 'Сумки, аксесуари', 'https://hotline.ua/ua/fashion/sumki-i-aksessuary/', 'fashion', 'Годинники, Сумки, Аксесуари', 21030),
    HotlineSeedTemplate('fashion-dlya-sporta', 'Одяг для спорту і відпочинку', 'fashion-dlya-sporta', 'Одяг для спорту і відпочинку', 'https://hotline.ua/ua/fashion/dlya-sporta/', 'fashion', 'Годинники, Сумки, Аксесуари', 21040),
)

# Backward-compatible name for tests and template import code. Runtime ingestion
# reads active HotlineSeed rows from the database.
HotlineSeed = HotlineSeedTemplate
HOTLINE_SEEDS = HOTLINE_SEED_TEMPLATES


def get_hotline_seed_template(seed_key: str) -> HotlineSeedTemplate:
    for seed in HOTLINE_SEED_TEMPLATES:
        if seed.key == seed_key:
            return seed
    raise KeyError(seed_key)
