# Generated by Django 6.0.1 on 2026-02-22 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gifts', '0002_giftimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('website', models.URLField()),
                ('shop_type', models.CharField(choices=[('marketplace', 'Marketplace'), ('specialized', 'Specialized'), ('brand', 'Brand')], max_length=20)),
                ('specialization', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shops/static/images/')),
                ('primary_color', models.CharField(default='#000000', max_length=7)),
                ('has_affiliate', models.BooleanField(default=False)),
                ('affiliate_parameter', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('total_products', models.IntegerField(default=0)),
                ('click_count', models.IntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, to='gifts.category')),
            ],
            options={
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='ProductLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_url', models.URLField(max_length=500)),
                ('product_name', models.CharField(max_length=300)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('stock_quantity', models.IntegerField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('last_price_update', models.DateTimeField(blank=True, null=True)),
                ('click_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productlinks', to='gifts.gift')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productlinks', to='shops.shop')),
            ],
        ),
        migrations.CreateModel(
            name='ShopClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(max_length=300)),
                ('referrer', models.URLField(blank=True, max_length=500, null=True)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('product_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='shops.productlink')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_clicks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('in_stock', models.BooleanField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('product_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='shops.productlink')),
            ],
            options={
                'indexes': [models.Index(fields=['product_link', '-recorded_at'], name='shops_price_product_e1d487_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['shop_type', '-priority'], name='shops_shop_shop_ty_4570e8_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['-click_count'], name='shops_shop_click_c_3184eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='shop',
            constraint=models.CheckConstraint(condition=models.Q(('conversion_rate__gte', 0), ('conversion_rate__lte', 100)), name='shop_conversion_rate_range'),
        ),
        migrations.AddIndex(
            model_name='productlink',
            index=models.Index(fields=['shop', 'price'], name='shops_produ_shop_id_4d37ce_idx'),
        ),
        migrations.AddIndex(
            model_name='productlink',
            index=models.Index(fields=['in_stock', 'price'], name='shops_produ_in_stoc_19aacc_idx'),
        ),
        migrations.AddIndex(
            model_name='productlink',
            index=models.Index(fields=['last_price_update'], name='shops_produ_last_pr_449a17_idx'),
        ),
        migrations.AddIndex(
            model_name='productlink',
            index=models.Index(fields=['gift'], name='shops_produ_gift_id_84675f_idx'),
        ),
        migrations.AddConstraint(
            model_name='productlink',
            constraint=models.UniqueConstraint(fields=('gift', 'shop'), name='unique_gift_shop'),
        ),
        migrations.AddConstraint(
            model_name='productlink',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='productlink_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='productlink',
            constraint=models.CheckConstraint(condition=models.Q(('original_price__isnull', True), ('original_price__gte', models.F('price')), _connector='OR'), name='productlink_original_gte_price'),
        ),
        migrations.AddIndex(
            model_name='shopclick',
            index=models.Index(fields=['product_link', '-clicked_at'], name='shops_shopc_product_b39efc_idx'),
        ),
        migrations.AddIndex(
            model_name='shopclick',
            index=models.Index(fields=['user', '-clicked_at'], name='shops_shopc_user_id_f2e108_idx'),
        ),
        migrations.AddIndex(
            model_name='shopclick',
            index=models.Index(fields=['-clicked_at'], name='shops_shopc_clicked_359114_idx'),
        ),
        migrations.AddIndex(
            model_name='shopclick',
            index=models.Index(fields=['session_key'], name='shops_shopc_session_bb11be_idx'),
        ),
    ]
