# Generated by Django 6.0.1 on 2026-02-27 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0002_giftimage'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlink',
            name='category_confidence',
            field=models.FloatField(blank=True, help_text='Algorithm confidence score for category match (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='productlink',
            name='needs_category_review',
            field=models.BooleanField(db_index=True, default=False, help_text='Flagged for manual category review'),
        ),
        migrations.AddField(
            model_name='productlink',
            name='original_category_name',
            field=models.CharField(blank=True, default='', help_text='Original category or breadcrumbs from the source shop', max_length=300),
        ),
        migrations.AddIndex(
            model_name='productlink',
            index=models.Index(fields=['needs_category_review', 'shop'], name='shops_produ_needs_c_8bce3f_idx'),
        ),
    ]
