# Generated by Django 6.0.1 on 2026-02-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_productlink_category_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlink',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Image URL'),
        ),
    ]
