# Generated by Django 6.0.1 on 2026-05-08 09:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit


def normalize_product_url(url):
    if not url:
        return ""

    parts = urlsplit(url.strip())
    query = urlencode(sorted(parse_qsl(parts.query, keep_blank_values=True)))
    path = parts.path.rstrip("/") or "/"
    return urlunsplit((parts.scheme.lower(), parts.netloc.lower(), path, query, ""))


def populate_offer_defaults(apps, schema_editor):
    ProductLink = apps.get_model("shops", "ProductLink")
    Shop = apps.get_model("shops", "Shop")
    ShopIntegration = apps.get_model("shops", "ShopIntegration")
    ShopSource = apps.get_model("shops", "ShopSource")

    for offer in ProductLink.objects.all().only("id", "product_url"):
        ProductLink.objects.filter(id=offer.id).update(
            normalized_product_url=normalize_product_url(offer.product_url)
        )

    rozetka_shop = Shop.objects.filter(slug="rozetka").first()
    if rozetka_shop is None:
        return

    integration, _ = ShopIntegration.objects.get_or_create(
        shop=rozetka_shop,
        connector_type="marketplace_template",
        base_url=rozetka_shop.website,
        defaults={
            "auth_type": "none",
            "request_config": {"template": "rozetka"},
            "field_mapping": {},
            "is_active": True,
            "priority": 0,
        },
    )
    ShopSource.objects.get_or_create(
        integration=integration,
        source_type="category_url",
        value="https://rozetka.com.ua/ua/notebooks/c80004/",
        defaults={
            "config": {"category_hint": "notebooks"},
            "is_active": True,
            "priority": 0,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0003_gift_image_url'),
        ('shops', '0003_productlink_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCategoryAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_category', models.CharField(max_length=300)),
                ('normalized_category', models.CharField(db_index=True, max_length=300)),
                ('confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('matched', 'Matched'), ('ignored', 'Ignored')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shop category alias',
                'verbose_name_plural': 'Shop category aliases',
            },
        ),
        migrations.CreateModel(
            name='ShopIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_type', models.CharField(choices=[('json_api', 'JSON API'), ('xml_feed', 'XML Feed'), ('html_search_template', 'HTML Search Template'), ('marketplace_template', 'Marketplace Template')], max_length=50)),
                ('base_url', models.URLField(max_length=500)),
                ('auth_type', models.CharField(choices=[('none', 'None'), ('bearer_token', 'Bearer token'), ('api_key_header', 'API key in header'), ('api_key_query', 'API key in query'), ('basic', 'Basic auth')], default='none', max_length=30)),
                ('auth_config', models.JSONField(blank=True, default=dict)),
                ('request_config', models.JSONField(blank=True, default=dict)),
                ('field_mapping', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shop integration',
                'verbose_name_plural': 'Shop integrations',
                'ordering': ['-priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShopSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('category_url', 'Category URL'), ('search_template', 'Search template'), ('feed_url', 'Feed URL'), ('api_endpoint', 'API endpoint'), ('seed_query', 'Seed query')], max_length=30)),
                ('value', models.TextField()),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shop source',
                'verbose_name_plural': 'Shop sources',
                'ordering': ['-priority', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='productlink',
            options={'verbose_name': 'Product offer', 'verbose_name_plural': 'Product offers'},
        ),
        migrations.RemoveConstraint(
            model_name='productlink',
            name='unique_gift_shop',
        ),
        migrations.AddField(
            model_name='productlink',
            name='external_offer_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productlink',
            name='external_product_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productlink',
            name='is_marketplace_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productlink',
            name='normalized_product_url',
            field=models.CharField(blank=True, db_index=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='productlink',
            name='seller_external_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productlink',
            name='seller_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productlink',
            name='seller_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shopcategoryalias',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_aliases', to='gifts.category'),
        ),
        migrations.AddField(
            model_name='shopcategoryalias',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_aliases', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='shopintegration',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='shopsource',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='shops.shopintegration'),
        ),
        migrations.AddField(
            model_name='productlink',
            name='discovered_via_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_links', to='shops.shopsource'),
        ),
        migrations.RunPython(populate_offer_defaults, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='productlink',
            index=models.Index(fields=['gift', 'shop', 'price'], name='shops_produ_gift_id_9f0bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='productlink',
            index=models.Index(fields=['shop', 'seller_name'], name='shops_produ_shop_id_2d1b8d_idx'),
        ),
        migrations.AddIndex(
            model_name='productlink',
            index=models.Index(fields=['shop', 'external_product_id'], name='shops_produ_shop_id_67ac96_idx'),
        ),
        migrations.AddConstraint(
            model_name='productlink',
            constraint=models.UniqueConstraint(condition=models.Q(('external_offer_id__isnull', False), models.Q(('external_offer_id', ''), _negated=True)), fields=('shop', 'external_offer_id'), name='unique_shop_external_offer_id'),
        ),
        migrations.AddConstraint(
            model_name='productlink',
            constraint=models.UniqueConstraint(condition=models.Q(('normalized_product_url', ''), _negated=True), fields=('shop', 'normalized_product_url'), name='unique_shop_normalized_product_url'),
        ),
        migrations.AddIndex(
            model_name='shopcategoryalias',
            index=models.Index(fields=['shop', 'status'], name='shops_shopc_shop_id_912677_idx'),
        ),
        migrations.AddIndex(
            model_name='shopcategoryalias',
            index=models.Index(fields=['shop', 'normalized_category'], name='shops_shopc_shop_id_f802bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='shopcategoryalias',
            constraint=models.UniqueConstraint(fields=('shop', 'raw_category'), name='unique_shop_raw_category'),
        ),
        migrations.AddIndex(
            model_name='shopintegration',
            index=models.Index(fields=['shop', 'is_active', '-priority'], name='shops_shopi_shop_id_f764cc_idx'),
        ),
        migrations.AddIndex(
            model_name='shopintegration',
            index=models.Index(fields=['connector_type', 'is_active'], name='shops_shopi_connect_c137b8_idx'),
        ),
        migrations.AddIndex(
            model_name='shopsource',
            index=models.Index(fields=['integration', 'is_active', '-priority'], name='shops_shops_integra_e04d28_idx'),
        ),
        migrations.AddIndex(
            model_name='shopsource',
            index=models.Index(fields=['source_type', 'is_active'], name='shops_shops_source__32343d_idx'),
        ),
    ]
