# Generated by Django 6.0.1 on 2026-05-08 11:40

from django.db import migrations, models


def populate_discovery_modes(apps, schema_editor):
    ShopSource = apps.get_model("shops", "ShopSource")
    mapping = {
        "category_url": "category_seed",
        "search_template": "query_seed",
        "seed_query": "query_seed",
        "feed_url": "feed",
        "api_endpoint": "api_catalog",
    }
    for source_type, discovery_mode in mapping.items():
        ShopSource.objects.filter(source_type=source_type).update(discovery_mode=discovery_mode)


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0004_shopcategoryalias_shopintegration_shopsource_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsource",
            name="discovery_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("category_seed", "Category seed"),
                    ("query_seed", "Query seed"),
                    ("feed", "Feed"),
                    ("api_catalog", "API catalog"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.RunPython(populate_discovery_modes, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="shopsource",
            index=models.Index(fields=["discovery_mode", "is_active"], name="shops_shops_discove_0bb522_idx"),
        ),
    ]
