# Generated by Django 6.0.1 on 2026-05-13 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_shopsource_discovery_mode'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='shopintegration',
            name='shops_shopi_shop_id_f764cc_idx',
        ),
        migrations.RemoveIndex(
            model_name='shopintegration',
            name='shops_shopi_connect_c137b8_idx',
        ),
        migrations.RemoveIndex(
            model_name='shopsource',
            name='shops_shops_integra_e04d28_idx',
        ),
        migrations.RemoveIndex(
            model_name='shopsource',
            name='shops_shops_source__32343d_idx',
        ),
        migrations.RemoveIndex(
            model_name='shopsource',
            name='shops_shops_discove_0bb522_idx',
        ),
        migrations.RemoveField(
            model_name='productlink',
            name='discovered_via_source',
        ),
        migrations.RemoveField(
            model_name='shopsource',
            name='integration',
        ),
        migrations.DeleteModel(
            name='ShopIntegration',
        ),
        migrations.DeleteModel(
            name='ShopSource',
        ),
    ]
