"""
Django settings for gift_idea_generator project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path
from typing import Mapping
from urllib.parse import quote

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


def build_database_config() -> dict:
    database_url = os.getenv("DATABASE_URL")
    if database_url:
        return dj_database_url.parse(database_url)

    db_name = os.getenv("DB_NAME")
    db_user = os.getenv("DB_USER")
    db_password = os.getenv("DB_PASSWORD")
    db_host = os.getenv("DB_HOST", "127.0.0.1")
    db_port = os.getenv("DB_PORT", "5432")

    if not all([db_name, db_user, db_password]):
        raise ImproperlyConfigured(
            "Set DATABASE_URL or DB_NAME, DB_USER, and DB_PASSWORD.",
        )

    return {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": db_name,
        "USER": db_user,
        "PASSWORD": db_password,
        "HOST": db_host,
        "PORT": db_port,
    }


def build_redis_url() -> str:
    broker_url = os.getenv("CELERY_BROKER_URL")
    if broker_url:
        return broker_url

    redis_host = os.getenv("REDIS_HOST", "127.0.0.1")
    redis_port = os.getenv("REDIS_PORT", "6379")
    redis_db = os.getenv("REDIS_DB", "0")

    redis_password = os.getenv("REDIS_PASSWORD")
    if redis_password:
        quoted_password = quote(redis_password, safe="")
        return f"redis://:{quoted_password}@{redis_host}:{redis_port}/{redis_db}"

    return f"redis://{redis_host}:{redis_port}/{redis_db}"


SCRAPING_USER_AGENT = os.getenv("SCRAPING_USER_AGENT", "").strip()
DJANGO_LOG_LEVEL = os.getenv("DJANGO_LOG_LEVEL", "INFO").upper()


def _get_env(environ: Mapping[str, str] | None, key: str, default: str = "") -> str:
    source = os.environ if environ is None else environ
    return str(source.get(key, default)).strip()


def build_s3_media_storage_options(
    environ: Mapping[str, str] | None = None,
) -> dict:
    required_keys = (
        "MEDIA_S3_BUCKET_NAME",
        "MEDIA_S3_ACCESS_KEY_ID",
        "MEDIA_S3_SECRET_ACCESS_KEY",
    )
    missing_keys = [key for key in required_keys if not _get_env(environ, key)]
    if missing_keys:
        raise ImproperlyConfigured(
            "Set these variables when MEDIA_STORAGE_BACKEND=s3: "
            + ", ".join(missing_keys),
        )

    options = {
        "bucket_name": _get_env(environ, "MEDIA_S3_BUCKET_NAME"),
        "access_key": _get_env(environ, "MEDIA_S3_ACCESS_KEY_ID"),
        "secret_key": _get_env(environ, "MEDIA_S3_SECRET_ACCESS_KEY"),
        "region_name": _get_env(environ, "MEDIA_S3_REGION_NAME", "auto"),
        "location": _get_env(environ, "MEDIA_S3_LOCATION", "media").strip("/"),
        "querystring_auth": False,
        "file_overwrite": False,
        "object_parameters": {
            "CacheControl": _get_env(
                environ,
                "MEDIA_S3_CACHE_CONTROL",
                "max-age=86400",
            ),
        },
    }

    endpoint_url = _get_env(environ, "MEDIA_S3_ENDPOINT_URL")
    if endpoint_url:
        options["endpoint_url"] = endpoint_url

    custom_domain = _get_env(environ, "MEDIA_S3_CUSTOM_DOMAIN")
    if custom_domain:
        options["custom_domain"] = custom_domain

    return options


def build_default_storage_config(
    environ: Mapping[str, str] | None = None,
) -> dict:
    backend = _get_env(environ, "MEDIA_STORAGE_BACKEND", "local").lower()
    if backend == "local":
        return {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
            "OPTIONS": {
                "location": MEDIA_ROOT,
                "base_url": MEDIA_URL,
            },
        }
    if backend == "s3":
        return {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": build_s3_media_storage_options(environ),
        }
    raise ImproperlyConfigured(
        "MEDIA_STORAGE_BACKEND must be either 'local' or 's3'.",
    )


def build_staticfiles_storage_config() -> dict:
    if DEBUG:
        return {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        }
    return {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    }


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    # Third-party apps
    'rest_framework',           # API endpoints
    'django_filters',           # Advanced filtering
    'corsheaders',              # CORS for API

    'gift_idea_generator',
    'gifts',
    'shops',
    'home',
    'search',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gift_idea_generator.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gift_idea_generator.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': build_database_config(),
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'uk'

TIME_ZONE = 'Europe/Kyiv'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STORAGES = {
    "default": build_default_storage_config(),
    "staticfiles": build_staticfiles_storage_config(),
}

# Celery
CELERY_BROKER_URL = build_redis_url()
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_ROUTES = {
    'search.tasks.enqueue_missing_hotline_seed_refreshes': {'queue': 'discovery'},
    'search.tasks.enqueue_hotline_seed_refreshes': {'queue': 'discovery'},
    'search.tasks.enqueue_stale_hotline_product_refreshes': {'queue': 'prices'},
    'search.tasks.refresh_hotline_seed': {'queue': 'discovery'},
    'search.tasks.refresh_hotline_product': {'queue': 'prices'},
    'shops.tasks.update_gift_price_cache': {'queue': 'prices'},
    'shops.tasks.verify_product_link': {'queue': 'verification'},
    'shops.tasks.increment_shop_click': {'queue': 'prices'},
    'shops.tasks.trigger_all_verifications': {'queue': 'verification'},
}

CELERY_BEAT_SCHEDULE = {
    "hotline-cold-start-bootstrap-guard": {
        "task": "search.tasks.enqueue_missing_hotline_seed_refreshes",
        "schedule": timedelta(minutes=5),
    },
    "hotline-seed-refresh": {
        "task": "search.tasks.enqueue_hotline_seed_refreshes",
        "schedule": timedelta(hours=6),
    },
    "hotline-stale-product-refresh": {
        "task": "search.tasks.enqueue_stale_hotline_product_refreshes",
        "schedule": timedelta(hours=1),
        "args": (100,),
    },
    "product-link-verification": {
        "task": "shops.tasks.trigger_all_verifications",
        "schedule": timedelta(hours=6),
    },
}

# Logging
LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'scraper_file': {
            'class': 'logging.FileHandler',
            'filename': LOG_DIR / 'scraper.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'shops.tasks': {
            'handlers': ['console', 'scraper_file'],
            'level': DJANGO_LOG_LEVEL,
            'propagate': False,
        },
        'search.hotline': {
            'handlers': ['console', 'scraper_file'],
            'level': DJANGO_LOG_LEVEL,
            'propagate': False,
        },
        'search.services': {
            'handlers': ['console', 'scraper_file'],
            'level': DJANGO_LOG_LEVEL,
            'propagate': False,
        },
        'search.tasks': {
            'handlers': ['console', 'scraper_file'],
            'level': DJANGO_LOG_LEVEL,
            'propagate': False,
        },
    },
}

# DRF
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
    ],
}
