# Generated by Django 6.0.1 on 2026-05-08 18:21

import django.utils.timezone
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gifts', '0003_gift_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('seed_refresh', 'Seed refresh'), ('product_refresh', 'Product refresh')], db_index=True, max_length=30)),
                ('seed_key', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('source_product_id', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('discovered_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_runs', to='gifts.gift')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['task_type', 'status'], name='search_inge_task_ty_5f059e_idx'), models.Index(fields=['task_type', 'seed_key', '-updated_at'], name='search_inge_task_ty_6bb6cc_idx'), models.Index(fields=['task_type', 'source_product_id', '-updated_at'], name='search_inge_task_ty_850850_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchIngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('hotline', 'Hotline')], default='hotline', max_length=20)),
                ('query', models.CharField(max_length=255)),
                ('normalized_query', models.CharField(db_index=True, max_length=255)),
                ('request_filters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('gift_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gifts', models.ManyToManyField(blank=True, related_name='search_ingestion_jobs', to='gifts.gift')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['source', 'status'], name='search_sear_source_67921a_idx'), models.Index(fields=['source', '-updated_at'], name='search_sear_source_a074a7_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'normalized_query'), name='unique_source_normalized_query')],
            },
        ),
    ]
